#!/bin/bash
#rm -rf VMMRdb/ford*
#rm -rf VMMRdb/chevrolet*
#rm -rf VMMRdb/toyota*
#rm -rf VMMRdb/honda*
#rm -rf VMMRdb/nissan*
#rm -rf VMMRdb/dodge*
#rm -rf VMMRdb/volkswagen*
#rm -rf VMMRdb/jeep*
#rm -rf VMMRdb/bmw*
#rm -rf VMMRdb/hyundai*
#rm -rf VMMRdb/chrysler*
#rm -rf VMMRdb/gmc*
#rm -rf VMMRdb/pontiac*
#rm -rf VMMRdb/mazda*
#rm -rf VMMRdb/mercedes*
#rm -rf VMMRdb/acura*
#rm -rf VMMRdb/kia*
#rm -rf VMMRdb/cadillac*
#rm -rf VMMRdb/mitsubishi*
#rm -rf VMMRdb/subaru*
#rm -rf VMMRdb/lexus*
#rm -rf VMMRdb/audi*
#rm -rf VMMRdb/mercury*
#rm -rf VMMRdb/volvo*
#rm -rf VMMRdb/buick*
#rm -rf VMMRdb/infiniti*
#rm -rf VMMRdb/lincoln*
#rm -rf VMMRdb/saturn*
#rm -rf VMMRdb/oldsmobile*
#rm -rf VMMRdb/scion*
#rm -rf VMMRdb/mini*
#rm -rf VMMRdb/suzuki*

# ALL BRANDS UNDER 1000 PHOTOS

rm -rf VMMRdb/jaguar*
rm -rf VMMRdb/porsche*
rm -rf VMMRdb/isuzu*
rm -rf VMMRdb/plymouth*
rm -rf VMMRdb/landrover*
rm -rf VMMRdb/saab*
rm -rf VMMRdb/hummer*
rm -rf VMMRdb/ram*
rm -rf VMMRdb/smart*
rm -rf VMMRdb/fiat*
rm -rf VMMRdb/eagle*
rm -rf VMMRdb/daewoo*
rm -rf VMMRdb/mg*
rm -rf VMMRdb/maserati*
rm -rf VMMRdb/datsun*
rm -rf VMMRdb/amc*
rm -rf VMMRdb/triumph*
rm -rf VMMRdb/am*
rm -rf VMMRdb/ferrari*
rm -rf VMMRdb/bentley*
rm -rf VMMRdb/studebaker*
rm -rf VMMRdb/rollsroyce*
rm -rf VMMRdb/alfa*
rm -rf VMMRdb/lotus*
rm -rf VMMRdb/rambler*
rm -rf VMMRdb/willys*
rm -rf VMMRdb/bradley*
rm -rf VMMRdb/can*
rm -rf VMMRdb/daihatsu*
rm -rf VMMRdb/opel*
rm -rf VMMRdb/citroen*
rm -rf VMMRdb/holden*
rm -rf VMMRdb/packard*
rm -rf VMMRdb/blakely*
rm -rf VMMRdb/peugeot*
rm -rf VMMRdb/tesla*
rm -rf VMMRdb/morris*
rm -rf VMMRdb/sunbeam*
rm -rf VMMRdb/aston*
rm -rf VMMRdb/lamborghini*
rm -rf VMMRdb/polaris*
rm -rf VMMRdb/renault*
rm -rf VMMRdb/nash*
